### ISSUE TITLE
Unable to establish connection to keystone in alarm container.

### ISSUE THREAD

**Issue by superbag2010** [monasca/monasca-docker#118]
When I commanded "docker-compose up", other containers worked well. However, 'monascadocker_alarms_1' container was exited after some time.
![image](https://user-images.githubusercontent.com/17903225/28267024-17afcf00-6b33-11e7-9c58-14393a1d38ec.png)

I searched alarm container log. At first, it said like following. In that time, alarm container was alive yet.
![image](https://user-images.githubusercontent.com/17903225/28266838-1876bd3c-6b32-11e7-943e-0e1ca6f90357.png)

I tried to configure 'OS_AUTH_URL' several times in docker-compose.yml, but I always got the same error log(above image). Could you let me know proper 'OS_AUTH_URL'? Thank you.

**Comment by timothyb89** [comment]
Hi,

We have several containers that run briefly at startup and exit, including alarms, mysql-init, influxdb-init, etc. The log messages you see are the container attempting to connect to services (like keystone or monasca-api) that are still starting up, so some number of failures and retries is expected.

If there was an issue (like a service failing to come up within the timeout period) the alarms container would return non-zero and would output some additional log info. In this case the container exited successfully which is the expected behavior.
